# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easyfl/pb/server_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from easyfl.pb import common_pb2 as easyfl_dot_pb_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x65\x61syfl/pb/server_service.proto\x12\teasyfl.pb\x1a\x16\x65\x61syfl/pb/common.proto\"p\n\rUploadRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08round_id\x18\x02 \x01(\x05\x12\x11\n\tclient_id\x18\x03 \x01(\x05\x12)\n\x07\x63ontent\x18\x04 \x01(\x0b\x32\x18.easyfl.pb.UploadContent\",\n\rUploadContent\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05\x65xtra\x18\x63 \x01(\x0c\"-\n\x0bPerformance\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x02\x12\x0c\n\x04loss\x18\x02 \x01(\x02\"3\n\x0eUploadResponse\x12!\n\x06status\x18\x01 \x01(\x0b\x32\x11.easyfl.pb.Status\"W\n\nRunRequest\x12\r\n\x05model\x18\x01 \x01(\x0c\x12\"\n\x07\x63lients\x18\x02 \x03(\x0b\x32\x11.easyfl.pb.Client\x12\x16\n\x0e\x65tcd_addresses\x18\x03 \x01(\t\"0\n\x0bRunResponse\x12!\n\x06status\x18\x01 \x01(\x0b\x32\x11.easyfl.pb.Status\"\r\n\x0bStopRequest\"1\n\x0cStopResponse\x12!\n\x06status\x18\x01 \x01(\x0b\x32\x11.easyfl.pb.Status\";\n\x06\x43lient\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\r\n\x05index\x18\x03 \x01(\x05\x32\x88\x02\n\rServerService\x12?\n\x06Upload\x12\x18.easyfl.pb.UploadRequest\x1a\x19.easyfl.pb.UploadResponse\"\x00\x12\x43\n\nUpload_DQN\x12\x18.easyfl.pb.UploadRequest\x1a\x19.easyfl.pb.UploadResponse\"\x00\x12\x36\n\x03Run\x12\x15.easyfl.pb.RunRequest\x1a\x16.easyfl.pb.RunResponse\"\x00\x12\x39\n\x04Stop\x12\x16.easyfl.pb.StopRequest\x1a\x17.easyfl.pb.StopResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'easyfl.pb.server_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPLOADREQUEST']._serialized_start=69
  _globals['_UPLOADREQUEST']._serialized_end=181
  _globals['_UPLOADCONTENT']._serialized_start=183
  _globals['_UPLOADCONTENT']._serialized_end=227
  _globals['_PERFORMANCE']._serialized_start=229
  _globals['_PERFORMANCE']._serialized_end=274
  _globals['_UPLOADRESPONSE']._serialized_start=276
  _globals['_UPLOADRESPONSE']._serialized_end=327
  _globals['_RUNREQUEST']._serialized_start=329
  _globals['_RUNREQUEST']._serialized_end=416
  _globals['_RUNRESPONSE']._serialized_start=418
  _globals['_RUNRESPONSE']._serialized_end=466
  _globals['_STOPREQUEST']._serialized_start=468
  _globals['_STOPREQUEST']._serialized_end=481
  _globals['_STOPRESPONSE']._serialized_start=483
  _globals['_STOPRESPONSE']._serialized_end=532
  _globals['_CLIENT']._serialized_start=534
  _globals['_CLIENT']._serialized_end=593
  _globals['_SERVERSERVICE']._serialized_start=596
  _globals['_SERVERSERVICE']._serialized_end=860
# @@protoc_insertion_point(module_scope)
